### ISSUE TITLE
day badge should change at 6am instead of midnight

### ISSUE THREAD

**Issue by LeMoonStar** [joblo2213/AoC-badges#1]
The aoc-badges workflow updated my readme to count 6 completed days, though I had only completed 5 days and at the time it updated the readme, the challenges for the day weren't even public.
the commit can be seen [here](https://github.com/LeMoonStar/AoC20/commit/5d85b8ed3ab36b54eb875c39583a49194ff682d5)

**Comment by J0B10** [comment]
It intentionally displays the **current day** not the completed days.

The reason for it updating before the puzzle goes live is that it just looks at the date.  Might look into this at some point but for now this is low priority as it can simply be fixed by changing the scheduler to 30 mins earlier or 6 hours later.

**Comment by LeMoonStar** [comment]
I honestly don't see the point in showing the current day, when it has nothing to do with the repository

**Comment by J0B10** [comment]
It's an advent calender. I personally prefer it that way. I don't really see the point of showing the completed days as its quite redundant to the stars.

**Comment by LeMoonStar** [comment]
well, still the current day says absolutely nothing about the project, so the current day is pretty redundant

**Comment by LeMoonStar** [comment]
so basically, only the star count has anything to do with the project

**Comment by J0B10** [comment]
> well, still the current day says absolutely nothing about the project, so the current day is pretty redundant

Yes, it manly serves as shortcut to the adventcalender and for stupid people like me who always forget the current date 😅
