### ISSUE TITLE
Ability to enable and disable certain badges

### ISSUE THREAD

**Issue by LeMoonStar** [joblo2213/AoC-badges#3]
Since we now have the **day** and the **days completed** badge(#2), it could be pretty confusing to some people which one means what.
Also, the **day** badge is not really useful to everyone

**Comment by J0B10** [comment]
If you don't have exactly these badges in your readme nothing happens so I don't really get what disabling the badges should do other than add more confusion.

Also you can already do that by just using a regex that matches nothing like `a^`. 

And I do get that you don't like the day badge but I do, so deal with it. 🙄 

To prevent any confusion I'll add some further description to the Readme.

**Comment by LeMoonStar** [comment]
> And I do get that you don't like the day badge but I do, so deal with it. roll_eyes
that was not the point of it, I understand that you want and need it, that's no problem.
I also didn't know that just removing the badge does this, but when thinking about it, yeah, it does make sense.
