### ISSUE TITLE
Configuring multiple years

### ISSUE THREAD

**Issue by developher-net** [joblo2213/AoC-badges#5]
How could we go about configuring for multiple years? I have all years in a single repo and would love to show status of each year.

**Comment by J0B10** [comment]
First of all thanks a lot for checking out the action and giving feedback.  
It was really just a small project to get to know github actions and spice up my aoc repo a bit.   
So great to see people from the other side of the world using it 😄👍 

For now you could just have the aoc badges action multiple times (once for each year) and have slightly different badges for each year with a custom regex (use `starsRegex` and `daysCompletedRegex` inputs).  
The day badge probably doesn't makes sense for multiple years as it only depends on the current date (and therefore only works in December).  
Also make sure to set the leader board url to the leader board of the proper year using the optional `leaderboard` import.  

It would make sense to add an additional `year` input to make that stuff easier. But I'll probably won't work on this before next aoc as this really is a December project.  I might then also tweak some other stuff to make it easier to use. 

If you have some more questions feel free or an example feel free to ask.
