### ISSUE TITLE
Simplify workflow setup for git commit

### ISSUE THREAD

**Issue by developher-net** [joblo2213/AoC-badges#6]
I would recommend simplifying the setup with a GitHub action for committing instead of recommending people create and store SSH keys:

https://github.com/marketplace/actions/git-auto-commit

**Comment by J0B10** [comment]
Yeah I agree I should have used git auto commit. Also the SSH key is not really needed even with the current config, as the token stored in `GITHUB_TOKEN` secret already has the needed permissions. 

I did not knew that back when I created the action.
